# Generated by Django 5.2.12 on 2026-03-07 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название модели')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг модели')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели товаров',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг категории')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/', verbose_name='Иконка')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='totembo.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название товара')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг товара')),
                ('desc', models.TextField(verbose_name='Описание товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('quantity', models.IntegerField(default=15, verbose_name='Кол-во товара')),
                ('color_name', models.CharField(max_length=50, verbose_name='Название цвета')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='totembo.category', verbose_name='Категория')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totembo.modelproduct', verbose_name='Модель товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ImagesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='totembo.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
            },
        ),
    ]
